"""2.0

Revision ID: 991705f763cf
Revises: 68927e50bc50
Create Date: 2023-04-28 22:31:47.459663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991705f763cf'
down_revision = '68927e50bc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
